from django.urls import path
from .views import (
    OperatorRegistrationAPIView,
    PendingOperatorListAPIView,
    ApproveOperatorAPIView,
    RejectOperatorAPIView,
    ActivateOperatorAPIView,
    DeactivateOperatorAPIView,
    AssignedRequestsAPIView,
    AddCreditAPIView,
    WalletAPIView,
    WalletHistoryAPIView,
    AdminOperatorTransactionsAPIView,
<<<<<<< HEAD
=======
    OperatorPointRequestCreateView,
    OperatorPointRequestListView,
    AdminPointRequestListView,
    AdminPointRequestActionView,
>>>>>>> 332fab01927346c87f0b547ac4c9f0dce9bbf7af
    AdminTransactionsAPIView,
)


urlpatterns = [
    path(
        "admin/operators/pending/",
        PendingOperatorListAPIView.as_view(),
        name="pending-operators",
    ),
    path(
        "admin/operators/<int:operator_id>/approve/",
        ApproveOperatorAPIView.as_view(),
        name="approve-operator",
    ),
    path(
        "admin/operators/<int:operator_id>/reject/",
        RejectOperatorAPIView.as_view(),
        name="reject-operator",
    ),
    path(
        "admin/operators/<int:operator_id>/activate/",
        ActivateOperatorAPIView.as_view(),
        name="activate-operator",
    ),
    path(
        "admin/operators/<int:operator_id>/deactivate/",
        DeactivateOperatorAPIView.as_view(),
        name="deactivate-operator",
    ),
    path(
        "requests/assigned/",
        AssignedRequestsAPIView.as_view(),
        name="assigned-requests",
    ),
    path(
        "wallet/add-credit/",
        AddCreditAPIView.as_view(),
        name="add-credit",
    ),
    path(
        "wallet/",
        WalletAPIView.as_view(),
        name="wallet",
    ),
    path(
        "wallet/history/",
        WalletHistoryAPIView.as_view(),
        name="wallet-history",
    ),
    path(
        "admin/operators/<int:operator_id>/transactions/",
        AdminOperatorTransactionsAPIView.as_view(),
        name="admin-operator-transactions",
    ),
    path(
<<<<<<< HEAD
=======
        "point-requests/",
        OperatorPointRequestListView.as_view(),
        name="operator-point-requests",
    ),
    path(
        "point-requests/create/",
        OperatorPointRequestCreateView.as_view(),
        name="operator-point-request-create",
    ),
    path(
        "admin/point-requests/",
        AdminPointRequestListView.as_view(),
        name="admin-point-requests",
    ),
    path(
        "admin/point-requests/<int:request_id>/<str:action>/",
        AdminPointRequestActionView.as_view(),
        name="admin-point-request-action",
    ),
    path(
>>>>>>> 332fab01927346c87f0b547ac4c9f0dce9bbf7af
        "admin/transactions/",
        AdminTransactionsAPIView.as_view(),
        name="admin-transactions",
    ),
]
