from django.urls import path
from .views import (
    OperatorRegistrationAPIView,
    PendingOperatorListAPIView,
    ApproveOperatorAPIView,
    RejectOperatorAPIView,
    ActivateOperatorAPIView,
    DeactivateOperatorAPIView,
    AssignedRequestsAPIView,
    AddCreditAPIView,
    WalletAPIView,
    WalletHistoryAPIView,
)


urlpatterns = [
    path(
        "admin/operators/pending/",
        PendingOperatorListAPIView.as_view(),
        name="pending-operators",
    ),
    path(
        "admin/operators/<int:operator_id>/approve/",
        ApproveOperatorAPIView.as_view(),
        name="approve-operator",
    ),
    path(
        "admin/operators/<int:operator_id>/reject/",
        RejectOperatorAPIView.as_view(),
        name="reject-operator",
    ),
    path(
        "admin/operators/<int:operator_id>/activate/",
        ActivateOperatorAPIView.as_view(),
        name="activate-operator",
    ),
    path(
        "admin/operators/<int:operator_id>/deactivate/",
        DeactivateOperatorAPIView.as_view(),
        name="deactivate-operator",
    ),
    path(
        "requests/assigned/",
        AssignedRequestsAPIView.as_view(),
        name="assigned-requests",
    ),
    path(
        "wallet/add-credit/",
        AddCreditAPIView.as_view(),
        name="add-credit",
    ),
    path(
        "wallet/",
        WalletAPIView.as_view(),
        name="wallet",
    ),
    path(
        "wallet/history/",
        WalletHistoryAPIView.as_view(),
        name="wallet-history",
    ),
]