# Generated by Django 5.2.9 on 2026-07-10 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    # The initial migration already contains this field.
    operations = []
