# Generated by Django 5.2.9 on 2026-07-11 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_name'),
    ]

    # These fields are already part of the initial migration.
    operations = []
