# Generated by Django 6.0.4 on 2026-07-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('from_location', models.CharField(max_length=100)),
                ('to_location', models.CharField(max_length=100)),
                ('journey_date', models.DateField()),
                ('total_tickets', models.PositiveIntegerField()),
                ('bus_type', models.CharField(choices=[('AC_SLEEPER', 'AC Sleeper'), ('NON_AC_SLEEPER', 'Non AC Sleeper'), ('AC_SEATER', 'AC Seater'), ('NON_AC_SEATER', 'Non AC Seater'), ('SEMI_SLEEPER', 'Semi Sleeper')], max_length=50)),
                ('expected_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ASSIGNED', 'Assigned'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='NEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
