# Generated by Django 6.0.4 on 2026-07-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrequests',
            name='request_id',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
