# Generated by Django 6.0.4 on 2026-07-09 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    # The initial migration already contains request_id.
    operations = []
