# Generated by Django 5.2.9 on 2026-07-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customerrequests_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrequests',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
