# Generated by Django 6.0.4 on 2026-07-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_customerrequests_assigned_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrequests',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
