# Generated by Django 6.0.7 on 2026-07-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_merge_0002_alter_customerrequests_id_0006_request_lifecycle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerrequests',
            name='contact_unlocked',
        ),
        migrations.RemoveField(
            model_name='customerrequests',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='customerrequests',
            name='public_token',
        ),
        migrations.AlterField(
            model_name='customerrequests',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('ASSIGNED', 'Assigned'), ('ACCEPTED', 'Accepted'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='NEW', max_length=20),
        ),
    ]
