# Generated by Django 6.0.7 on 2026-07-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_remove_customerrequests_contact_unlocked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrequests',
            name='request_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
