# Generated by Django 6.0.7 on 2026-07-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_alter_customerrequests_request_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrequests',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
