# Generated by Django 6.0.7 on 2026-07-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_customerrequests_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrequests',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('NEW', 'New'), ('ASSIGNED', 'Assigned'), ('ACCEPTED', 'Accepted'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20),
        ),
    ]
