# Generated by Django 6.0.4 on 2026-07-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_alter_customerrequests_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrequests',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
