# Generated by Django 6.0.4 on 2026-07-30 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_add_gender_to_customer_requests'),
        ('customer', '0013_alter_customerrequests_id'),
    ]

    operations = [
    ]
