# Generated by Django 6.0.7 on 2026-07-22 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0003_add_transaction_customer_request'),
        ('operators', '0003_pointrequest'),
    ]

    operations = [
    ]
