# Generated by Django 6.0.7 on 2026-08-11 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0004_merge_20260722_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('credit', 'Credit'), ('request', 'Request'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('info', 'Info')], default='info', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True, default='')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='operators.operator')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
