# Generated by Django 5.2.9 on 2026-07-16 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('from_location', models.CharField(max_length=100)),
                ('to_location', models.CharField(max_length=100)),
                ('journey_date', models.DateField()),
                ('journey_time', models.CharField(blank=True, max_length=20, null=True)),
                ('total_tickets', models.PositiveIntegerField()),
                ('bus_type', models.CharField(choices=[('AC_SLEEPER', 'AC Sleeper'), ('NON_AC_SLEEPER', 'Non AC Sleeper'), ('AC_SEATER', 'AC Seater'), ('NON_AC_SEATER', 'Non AC Seater'), ('SEMI_SLEEPER', 'Semi Sleeper')], max_length=50)),
                ('expected_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ASSIGNED', 'Assigned'), ('ACCEPTED', 'Accepted'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='NEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to='operators.operator')),
            ],
        ),
    ]
